/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.jul")
}

dependencies {
    api(project(":jul.communication"))
    api(project(":jul.schedule"))
    api(project(":jul.extension.type.processing"))
    api(project(":jul.communication.mqtt"))
    api("com.hivemq:hivemq-mqtt-client:_")
    api("org.testcontainers:junit-jupiter:_")  {
        exclude(group = "junit", module = "junit")
    }
    api("io.quarkus:quarkus-junit4-mock:_")
    api(Testing.junit.jupiter)
    api(Testing.junit.jupiter.api)
}

description = "JUL Extension MQTT Test"

java {
    withJavadocJar()
}
