/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.interface"))
    implementation(project(":jul.pattern"))
    implementation(project(":jul.extension.type.processing"))
}

description = "JUL Pattern Trigger"

java {
    withJavadocJar()
}
