/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation("org.openbase:type:[1.1,1.2-alpha)")
    implementation(project(":jul.extension.type.processing"))
    implementation(project(":jul.interface"))
    implementation(project(":jul.exception"))
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.10")
}

description = "JUL Communication Default"

java {
    withJavadocJar()
}
