/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.jul")
}

dependencies {
    api(project(":jul.extension.type.processing"))
    api(project(":jul.communication.mqtt"))
    api("java3d:vecmath:_")
    api("java3d:j3d-core:_")
    testImplementation("org.junit.jupiter:junit-jupiter:[5.8,5.9-alpha)")
    testImplementation ("org.junit.jupiter:junit-jupiter-api:[5.8,5.9-alpha)")
    testRuntimeOnly ("org.junit.jupiter:junit-jupiter-engine:[5.8,5.9-alpha)")
}

description = "JUL Transformation"

java {
    withJavadocJar()
}
