/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.processing.xml"))
    implementation(project(":jul.schedule"))
    implementation("org.apache.commons:commons-lang3:3.6")
}

description = "JUL Extension TCP"

java {
    withJavadocJar()
}
