/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":jul.interface"))
    api(project(":jul.schedule"))
    api(project(":jul.processing.json"))
    api("com.google.code.gson:gson:2.6.2")
    api("org.openbase:type:[1.1,1.2-alpha)")
}

description = "JUL Extension Protobuf"

java {
    withJavadocJar()
}
