/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.interface"))
    implementation(project(":jul.schedule"))
    implementation(project(":jul.processing.json"))
    implementation("com.google.code.gson:gson:2.6.2")
    implementation("org.openbase:type:[1.1,1.2-alpha)")
}

description = "JUL Extension Protobuf"

java {
    withJavadocJar()
}
