/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":jul.interface"))
    api(project(":jul.extension.type.interface"))
    api(project(":jul.schedule"))
    api("org.openjfx:javafx-base:16")
    api("org.openjfx:javafx-fxml:16")
    api("org.openjfx:javafx-graphics:16")
    api("org.openjfx:javafx-media:16")
    api("org.openjfx:javafx-controls:16")
    api("org.openjfx:javafx-base:16")
    api("org.openjfx:javafx-fxml:16")
    api("org.openjfx:javafx-graphics:16")
    api("org.openjfx:javafx-media:16")
    api("org.openjfx:javafx-controls:16")
    api("org.openjfx:javafx-base:16")
    api("org.openjfx:javafx-fxml:16")
    api("org.openjfx:javafx-graphics:16")
    api("org.openjfx:javafx-media:16")
    api("org.openjfx:javafx-controls:16")
    api("org.controlsfx:controlsfx:[9.0,9.1-alpha)")
    api("de.jensd:fontawesomefx:[8.9,8.10-alpha)")
    api("com.jfoenix:jfoenix:[9.0,9.1-alpha)")
}

description = "JUL Visual JavaFX"

java {
    withJavadocJar()
}
