/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.exception"))
    implementation(project(":jul.interface"))
    implementation(project(":jul.extension.protobuf"))
    implementation(project(":jul.processing"))
    implementation(project(":jul.schedule"))
    implementation("org.eclipse.jgit:org.eclipse.jgit:[5.1.7,5.1.8-alpha)")
    implementation("uk.com.robust-it:cloning:1.9.2")
    implementation(project(":jul.pattern.controller"))
}

description = "JUL Storage"

java {
    withJavadocJar()
}
