/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.jul")
}

dependencies {
    api(project(":jul.pattern"))
    api("commons-io:commons-io:_")
    api("commons-lang:commons-lang:_")
    api("java3d:vecmath:_")
}

description = "JUL Processing Default"

java {
    withJavadocJar()
}
