/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://mvn.cit-ec.de/nexus/content/repositories/releases/")
    }

    maven {
        url = uri("https://mvn.cit-ec.de/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://bits.netbeans.org/maven2/")
    }
}

dependencies {
    api("org.openbase:jps:[3.5,3.6-alpha)")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")
    testImplementation("org.junit.jupiter:junit-jupiter-api:[5.8,5.9-alpha)")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:[5.8,5.9-alpha)")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.6.10")
}

group = "org.openbase"
version = "3.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
