/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.jul")
}

dependencies {
    api(project(":jul.interface"))
    api("org.openbase:type:_")
    api(project(":jul.pattern"))
    api(project(":jul.extension.protobuf"))
}

description = "JUL Pattern Controller"

java {
    withJavadocJar()
}
