/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.schedule"))
    implementation("org.netbeans.external:AbsoluteLayout:RELEASE100")
    implementation(project(":jul.extension.type.interface"))
    implementation("org.openjfx:javafx-swing:16")
    implementation("org.openjfx:javafx-swing:16")
    implementation("org.openjfx:javafx-swing:16")
}

description = "JUL Visual Swing"

java {
    withJavadocJar()
}
