/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":jul.processing"))
    api(project(":jul.extension.type.processing"))
    api("org.openbase:type:1.1.3")
}

description = "JUL Extension RST Transform"

java {
    withJavadocJar()
}
