/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":jul.pattern"))
    api("commons-io:commons-io:2.11.0")
    api("commons-lang:commons-lang:2.6")
    api("java3d:vecmath:1.3.1")
}

description = "JUL Processing Default"

java {
    withJavadocJar()
}
