/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.jul")
}

dependencies {
    api(project(":jul.exception"))
    api(project(":jul.annotation"))
}

description = "JUL Interface"

java {
    withJavadocJar()
}
