/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    implementation(project(":jul.extension.protobuf"))
    implementation(project(":jul.extension.type.interface"))
    implementation(project(":jul.schedule"))
}

description = "JUL Extension RST Util"

java {
    withJavadocJar()
}
