/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api(project(":jul.communication"))
    api(project(":jul.communication.mqtt"))
    api(project(":jul.extension.type.interface"))
    api(project(":jul.extension.type.util"))
    api(project(":jul.exception"))
    api(project(":jul.extension.protobuf"))
    api(project(":jul.interface"))
    api(project(":jul.schedule"))
    api(project(":jul.pattern.controller"))
    testImplementation("org.testcontainers:testcontainers:1.16.3")
}

description = "JUL Extension Controller"

java {
    withJavadocJar()
}
