/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openbase.java-conventions")
}

dependencies {
    api("org.projectlombok:lombok:1.18.20")
}

description = "JUL Annoation"

java {
    withJavadocJar()
}
